- demo/build.gradle
- library/build.gradle
This was originally implemented in https://github.com/googlemaps/android-maps-utils/commit/85258dec6c217c5189b453478f691375f2a14db1 and https://github.com/googlemaps/android-maps-utils/commit/68609ef0c734b5971c9829fe11978ecd24816324, but seems to have been mistakenly reverted in the GeoJSON commit https://github.com/googlemaps/android-maps-utils/commit/46a4e20b034880c659689ff106931827ccaf2510.  As far as I can tell the other Google Play Services components aren't needed for GeoJSON.
> Include only maps component of Google Play Services library

- library/src/com/google/maps/android/clustering/view/DefaultClusterRenderer.java
I'd like to use the `DefaultClusterRenderer` in my project but override the colors.
This PR changes the access level of the `getColor` method so that it can be overridden in subclasses of `DefaultClusterRenderer`.
> Make getColor protected in DefaultClusterRenderer

- demo/AndroidManifest.xml
- demo/src/com/google/maps/android/utils/demo/MainActivity.java
- demo/src/com/google/maps/android/utils/demo/PolySimplifyDemoActivity.java
- library/src/com/google/maps/android/PolyUtil.java
- library/tests/src/com/google/maps/android/PolyUtilTest.java
* Douglas-Peucker implementation ported from the Google MyTracks project (https://code.google.com/p/mytracks/source/browse/MyTracks/src/com/google/android/apps/mytracks/util/LocationUtils.java#81), (c) Google 2008, licensed under Apache v2.0.
* Add demo activity for `PolyUtil.simplify()` - shows the original line in black, as well as simplified versions of the line with multiple tolerances in different colors
* Add unit tests for `PolyUtil.simplify()` and `PolyUtil.distanceToLine()` in `PolyUtilTest`
As discussed with @broady in https://github.com/googlemaps/android-maps-utils/pull/144#issuecomment-140505017.
@broady A few unrelated white space changes snuck into this commit via Android Studio - seems this happens on save, and I haven't found a way to disable it.  Let me know if this is …
> Add Douglas-Peucker line simplification algorithm as PolyUtil.simplify()

- .travis.yml
- README.md
- build.gradle
~~As discussed in https://github.com/googlemaps/android-maps-utils/issues/207#issuecomment-144904766, requires changing to `compileSdkVersion "Google Inc.:Google APIs:21"`, because:
a) Google API emulator image is needed to run tests that require Google Play Services (see https://developers.google.com/android/guides/setup)
b) the Google API Level 23 emulator seems to have a bug that doesn't allow installing/running tests from the command line~~
~~This patch also adds a command-line option to disable pre-dexing, which is used on Travis to decrease build times (see http://tools.android.com/tech-docs/new-build-system/tips#TOC-Improving-Build-Server-performance.)~~
See below comment for revised PR contents, based on comments on the initial commit.
> Fix #207 - Add Travis CI support

- library/src/com/google/maps/android/clustering/view/DefaultClusterRenderer.java
There are race conditions that seem to be able to result in multiple map initializations causing a null projection for a tiny amount of time, this will cause several crashes if we don't properly protect ourselves from them.
> Prevent crash on null Map Projection

- demo/src/com/google/maps/android/utils/demo/IconGeneratorDemoActivity.java
- library/src/com/google/maps/android/ui/IconGenerator.java
The underlying TextView API takes a CharSequence, so this is a simple change that lets us use different fonts etc when creating our icons. I've updated the sample app to show it in use.
> makeIcon takes CharSequence not String

- CONTRIBUTORS.md
- library/src/com/google/maps/android/clustering/algo/NonHierarchicalDistanceBasedAlgorithm.java
- library/src/com/google/maps/android/clustering/algo/StaticCluster.java
- library/tests/src/com/google/maps/android/clustering/QuadItemTest.java
- library/tests/src/com/google/maps/android/clustering/StaticClusterTest.java
This is a re-submission of https://github.com/googlemaps/android-maps-utils/pull/169 since I no longer have commit access to that one.
For reference, here's the original PR introduction:
> Adds implementations of "equals()" and "hashCode()" in StaticCluster and QuadItem classes. Benefit is the ability to reliably compare (and identify) instances of those classes.
> 
> As a bonus (and an implicit way to test QuadItem::hashCode() without exposing the inner class) this PR also includes an implementation of NonHierarchicalDistanceBasedAlgorithm::removeItem(). By the way, this would effectively fix issue #133.
> 
> PR commits include relevant tests. Let me know if more testing should be added.
> 
> Also, the added test files are new and thus copyrighted after myself, but still under the Apache …
> Equals for cluster subclasses

- library/src/com/google/maps/android/geojson/GeoJsonLineStringStyle.java
Added the setClickable method to make the LineString clickable.
> Added the setClickable method

- build.gradle
- demo/build.gradle
- gradle/wrapper/gradle-wrapper.properties
- library/build.gradle
PTAL @jfschmakeit @domesticmouse @barbeau 
Tests look fine but I'm very slightly concerned with using an unstable version of the gradle plugin. We can always revert this if we have to but I am thoroughly sick of restarting travis builds every goddamn day, so think it's worth the risk.
> Increasing ADB timeout to stabalise builds

- demo/src/com/google/maps/android/utils/demo/BaseDemoActivity.java
Contrary to our discussion, I opted to keep the base demo class - about half of the demos are structured in a way that depends on having a map member available, so it didn't make sense to restructure everything in an async way. PTAL @markmcd @jfschmakeit
> Replace deprecated getMap with getMapAsync in demo.

- build.gradle
- demo/res/values/strings.xml
- demo/src/com/google/maps/android/utils/demo/KmlDemoActivity.java
> Gradle version bump + updated KML URL for demo.

- demo/src/com/google/maps/android/utils/demo/GeoJsonDemoActivity.java
- library/src/com/google/maps/android/geojson/GeoJsonParser.java
- library/tests/src/com/google/maps/android/geojson/GeoJsonFeatureTest.java
GeoJson can contain null values, but the parser stored them as the string "null", this fixes that.
@markmcd PTAL
> Null GeoJson feature properties

- library/src/com/google/maps/android/kml/KmlRenderer.java
- library/src/com/google/maps/android/kml/KmlStyle.java
Major problem with [BitmapDescriptorFactory.fromPath(iconUrl)](https://developers.google.com/android/reference/com/google/android/gms/maps/model/BitmapDescriptorFactory.html) is that it requires **absolute** path and throws RuntimeException if file not found.
But KML files are often created with tools and by people who are not really aware of Android filesystem which gives:
```xml
<Style id='icon-ci-1-normal'>
<IconStyle>
<scale>1.1</scale>
<Icon>
<href>images/icon-1.png</href>
</Icon>
</IconStyle>
<LabelStyle>
<scale>0.0</scale>
</LabelStyle>
</Style>
```
And it would simply crash at `KmlStyle.setIconUrl`.
There are two approaches to solve this:
- Use `BitmapFactory.decodeFile(mIconUrl)` if `mIconUrl` is not really an URL, but a path on local FS
- Try to guess where the file is placed: …
> Decode marker icon from local FS

- library/src/com/google/maps/android/kml/KmlStyle.java
- library/tests/src/com/google/maps/android/kml/KmlStyleTest.java
As reported in #232 - I've verified My Maps exports KML colors as reported.
@markmcd PTAL
> Handle KML colors with missing leading zero

- build.gradle
- demo/build.gradle
- demo/src/com/google/maps/android/utils/demo/BigClusteringDemoActivity.java
- demo/src/com/google/maps/android/utils/demo/ClusteringDemoActivity.java
- demo/src/com/google/maps/android/utils/demo/CustomMarkerClusteringDemoActivity.java
- library/build.gradle
- library/src/com/google/maps/android/clustering/ClusterManager.java
Updates deprecated camera listener in clustering, as per: https://developers.google.com/maps/documentation/android-api/events#camera_change_events
PTAL @markmcd
> New camera listeners

- .travis.yml
* Add separate ANDOID_TAG ABI tag variable
* Duplicate tools to get the new `repository-11.xml` and to install Android SDK tools 25.1.x
* Change system image names to match new Android SDK
* Change emulator start command to use new ABI tag variable to specify Google APIs
See https://github.com/travis-ci/travis-ci/issues/6122#issuecomment-239073557 for details.
I tested this patch and [it passes](https://travis-ci.org/barbeau/android-maps-utils/builds/151550713).
A huuuuuge thanks to @ardock who shared his solution in the above Travis CI issue. :+1: :+1:
> Fix #284 - Tweak Travis script to fix Travis builds

- .github/ISSUE_TEMPLATE.md
See https://github.com/blog/2111-issue-and-pull-request-templates for how these work with Github.  It's similar to how the AOSP issue tracker injects template text when you open a new issue.
I've found that these templates result in better formatted issues and pull requests from outside contributors in projects I've worked on, and also force me to better document bug reports/PRs myself as a maintainer - having the template to drop text into streamlines the process significantly.
If there is anything here you don't want (e.g., squashing commits) or something missing, let me know and I'd be happy to update the PR.
> Add Github issue and pull request templates

- .travis.yml
- build.gradle
- demo/build.gradle
- gradle/wrapper/gradle-wrapper.properties
- library/build.gradle
This brings the project up-to-date with the current versions of:
* API Level
* Build Tools
* Google Maps library
* Android Gradle plugin
Travis script also modified for the above.  This allows use with Android Studio 2.2 as well.
API Level 24 emulator seems to be working, so I dropped the separate `EMULATOR_API_LEVEL` and am just using `ANDROID_API_LEVEL` for everything.
> Bump dependencies versions

- library/src/com/google/maps/android/quadtree/PointQuadTree.java
- library/tests/src/com/google/maps/android/quadtree/PointQuadTreeTest.java
I was able to repro #308 NPE by trying to remove an item before any item was inserted - I added a test case that repro's this NPE at the beginning of `PointQuadTreeTest.testMultiplePoints()`:
~~~
response = mTree.remove(item1);
assertFalse(response);
~~~
Adding a null check in `PointQuadTree.remove()` fixes this.
> Fix #308 - Add null check for removing item from uninitialized QuadTree

- library/src/com/google/maps/android/PolyUtil.java
In our project, we use different data structure to represent coordinates rather than `LatLng`. As a result, in order to utilize `containsLocation()`, we have to convert into `LatLng` which causes an allocation. So if we call it inside a loop through a list of coordinates, that will cause a lot more allocations.
For example:
```java
for (Location location : locations) {
if (PolyUtil.containsLocation(new LatLng(location.lat(), location.lng()), polygon, true)) {
return true;
}
}
```
So it'd be better if we don't allocate `LatLng`s:
```java
for (Location location : locations) {
if (PolyUtil.containsLocation(location.lat(), location.lng(), polygon, true)) {
return true;
}
}
```
> Add new containsLocation() that takes latitude and longitude instead `LatLng`

- library/src/com/google/maps/android/clustering/ClusterManager.java
- library/src/com/google/maps/android/clustering/view/ClusterRenderer.java
- library/src/com/google/maps/android/clustering/view/DefaultClusterRenderer.java
Option is now available to turn animations on or off via ClusterManager.
> Disable animations

- library/src/com/google/maps/android/PolyUtil.java
- library/tests/src/com/google/maps/android/PolyUtilTest.java
- library/tests/src/com/google/maps/android/data/kml/KmlPolygonTest.java
The methods provided to know whether a given location lies on the path of a polyline are good, but they could be even better if they also told where on the polyline the location is.
This in turn allows, for instance, to tap on any point on a polyline and get statistical information about the tapped point:
> Improve PolyUtil.isLocationOnPath to also tell where the location is on the polyline

- .travis.yml
It seems emulator-based unit testing is currently horribly broken due to issues with the API Level 23-25 emulators/SDK:
* API Level 23 - https://code.google.com/p/android/issues/detail?id=228113
* API Level 24/25 - https://code.google.com/p/android/issues/detail?id=230083 
...so for now change to just building the project on Travis (via `./gradlew clean assembleDebug`).
I'll keep tabs on the emulator testing and hopefully we can restore unit tests at some point in the future.  In the mean time we'll need to run tests locally.
> Don't run unit tests on Travis - just build the project

- library/src/com/google/maps/android/data/geojson/BiMultiMap.java
- library/tests/src/com/google/maps/android/data/geojson/BiMultiMapTest.java
**Changes**
- Explicitly call the Collection version of `put(key, value)` to correctly store the reverse relationship
The method `Renderer#addFeature(Feature feature)` calls the method `BiMultiMap#put` with an `Object` parameter. Java dynamic method dispatch does not work when passing objects as parameters, so the generic method `BiMultiMap#put(K key, Object object)` is always called, even when the created `mapObject` object is of type `Collection`.
> Storing Collection objects in BiMultiMap

- library/src/com/google/maps/android/data/kml/KmlStyle.java
stroke color isn't parsed in argb format.
> KmlStyle stroke color

- library/build.gradle
- library/src/com/google/maps/android/data/geojson/GeoJsonLineStringStyle.java
- library/src/com/google/maps/android/data/geojson/GeoJsonPointStyle.java
1. **Zindex** feature is added to **PointStyle of GeoJson** to facilitate placement of a point above or below
among multiple points
2. **LinePattern** feature is **added to LineStringStyle** to facilitate creation of dotted, dashed and other line style
Following screen shot displays uses of these features
>  Added Zindex in PointStyle and LinePattern in LineStringStyle of GeoJson

- library/src/com/google/maps/android/data/kml/KmlContainer.java
Because KmlPlacemarks returns StyleId's that are inside mStyleMap but containers only returns styles inside mStyles it is impossible to get all Styles. 
Add a method (getStyleIdFromMap) to get true style id from map.
> Method to get StyleId's from mStyleMap KmlContainer

- library/src/com/google/maps/android/clustering/algo/NonHierarchicalDistanceBasedAlgorithm.java
- library/src/com/google/maps/android/quadtree/PointQuadTree.java
ArrayList.remove() is a much more expensive operation than HashSet.remove(). Neither of these collections need to be an array, as neither order nor duplicate entries are required. A set collection is much more optimal with very noticeable speed improvements with large sets of cluster items.
> Optimized quad tree and cluster algorithm with HashSet instead of ArrayList

- library/src/com/google/maps/android/data/geojson/GeoJsonLineString.java
- library/src/com/google/maps/android/data/geojson/GeoJsonParser.java
- library/src/com/google/maps/android/data/geojson/GeoJsonPoint.java
- library/src/com/google/maps/android/data/kml/KmlFeatureParser.java
- library/src/com/google/maps/android/data/kml/KmlLineString.java
- library/src/com/google/maps/android/data/kml/KmlMultiTrack.java
- library/src/com/google/maps/android/data/kml/KmlPoint.java
- library/src/com/google/maps/android/data/kml/KmlTrack.java
- library/tests/src/com/google/maps/android/data/geojson/GeoJsonLineStringTest.java
- library/tests/src/com/google/maps/android/data/geojson/GeoJsonPointTest.java
- library/tests/src/com/google/maps/android/data/kml/KmlLineStringTest.java
- library/tests/src/com/google/maps/android/data/kml/KmlMultiTrackTest.java
- library/tests/src/com/google/maps/android/data/kml/KmlPointTest.java
- library/tests/src/com/google/maps/android/data/kml/KmlPolygonTest.java
- library/tests/src/com/google/maps/android/data/kml/KmlTrackTest.java
This pull request extends the KML file parsing capabilities by:
- adding support for altitudes to KmlPoint and KmlMultiline objects
- adding support for <Track> and <MultiTrack> geometries in KML files (including, of course, altitudes)
The change is backwards compatible: features have been added to existing objects but their pre-existing structure has otherwise been left untouched.
The new KmlTrack object inherits from KmlLineString.
The new KmlMultiTrack object inherits from KmlMultiGeometry and contains a list of KmlTrack objects.
Both objects, once parsed, can be rendered without further hassle with the existing infrastructure.
On an unrelated note, is there any particular reason why KmlParser is package private? I'm using this library to parse data from KML files and load it into my …
> Handle altitudes and parse Track and MultiTrack objects

- library/build.gradle
- library/src/com/google/maps/android/data/kml/KmlRenderer.java
and vice versa. HttpURLConnection does not follow these redirects natively (https://bugs.openjdk.java.net/browse/JDK-4620571). KMLs with image assets that redirect are unable to download.
> Handle 3xx redirects from HTTP to HTTPS

- library/src/com/google/maps/android/data/Renderer.java
- library/src/com/google/maps/android/data/geojson/GeoJsonPolygonStyle.java
setOnMapClickListener not called when clicking on map area with GeoJson polygon added. Polygon clickable option was set to true. Allow the user to set the clickable option.
Patch file with modified GeoJsonDemoActivity.java to test setting clickable style
[Demo_of_clickable_polygon_or_clicking_through.zip](https://github.com/googlemaps/android-maps-utils/files/1951404/Demo_of_clickable_polygon_or_clicking_through.zip)
> Set polygon clickable option with style instead of forced true.

- library/src/com/google/maps/android/SphericalUtil.java
- library/tests/src/com/google/maps/android/SphericalUtilTest.java
Hi, I got affected by issue #388 and thought I'd give the linear interpolation solution a try, since it is suggested in the discussion there (and the Wikipedia article linked in the code), and also seemed to give sensible results after trying it out for a couple of examples. Does this seem like a reasonable approach?
> Fall back to linear interpolation when interpolating in short distances (#388)

- gradle-mvn-push.gradle
- library/build.gradle
Make the project can be automatically compiled on [jitpack.io](https://jitpack.io/#googlemaps/android-maps-utils) by judging whether there is [a JITPACK variable](https://jitpack.io/docs/BUILDING/#build-environment).
> Config for JitPack.io

- library/src/com/google/maps/android/clustering/ClusterManager.java
- library/src/com/google/maps/android/clustering/algo/NonHierarchicalViewBasedAlgorithm.java
- library/src/com/google/maps/android/clustering/algo/ScreenBasedAlgorithm.java
Since ScreenBasedAlgorithm's GoogleMap.OnCameraChangeListener onCameraChange() method is only used within ClusterManager, it doesn't need to extend the deprecated listener.
> Fix deprecated API usage warnings

- library/src/com/google/maps/android/data/Feature.java
- library/src/com/google/maps/android/data/geojson/GeoJsonFeature.java
To prevent same name declaration issues for JSON fields. See issue #488.
> #488 Made Feature member id protected

- demo/res/values/strings.xml
Solves the following error:
java.io.IOException: Cleartext HTTP traffic to googlemaps.github.io not permitted
at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:115)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:458)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:244)
at java.net.URL.openStream(URL.java:1072)
at com.google.maps.android.utils.demo.KmlDemoActivity$DownloadKmlFile.doInBackground(KmlDemoActivity.java:88)
at com.google.maps.android.utils.demo.KmlDemoActivity$DownloadKmlFile.doInBackground(KmlDemoActivity.java:79)
at …
> Use HTTPS for demo KML Url

- build.gradle
Android Studio 3.5.1 is now available:
https://androidstudio.googleblog.com/2019/10/android-studio-351-available.html
> Update Android Gradle plugin to 3.5.1

- library/build.gradle
- library/tests/src/com/google/maps/android/clustering/StaticClusterTest.java
- library/tests/src/com/google/maps/android/data/LineStringTest.java
- library/tests/src/com/google/maps/android/data/geojson/GeoJsonLineStringStyleTest.java
- library/tests/src/com/google/maps/android/data/geojson/GeoJsonPointStyleTest.java
- library/tests/src/com/google/maps/android/data/geojson/GeoJsonPolygonStyleTest.java
- library/tests/src/com/google/maps/android/data/kml/KmlContainerParserTest.java
- library/tests/src/com/google/maps/android/data/kml/KmlFeatureParserTest.java
- library/tests/src/com/google/maps/android/data/kml/KmlLineStringTest.java
- library/tests/src/com/google/maps/android/data/kml/KmlParserTest.java
- library/tests/src/com/google/maps/android/data/kml/KmlPointTest.java
- library/tests/src/com/google/maps/android/data/kml/KmlStyleTest.java
- library/tests/src/com/google/maps/android/quadtree/PointQuadTreeTest.java
Background: @ming13 initially opened #529 on June 13 which contained similar changes. Back then, the project was not using androidx dependencies yet, so a couple more changes were required to make it work with the latest `master` branch.
To test this, run:
```
./gradlew :library:connectedCheck
```
Notice that on the current `master` branch, the tests are broken. With this PR merged, the existing tests will pass.
More follow-up test fixes will be required - The rebased #529 will move test resources, and hopefully we can convert these to pure unit tests so that a connected device is no longer required.
For now, these are the _minimal_ changes required to restore the ability to run the existing tests.
> Fix test setup

- library/src/com/google/maps/android/clustering/ClusterManager.java
- library/src/com/google/maps/android/clustering/view/DefaultClusterRenderer.java
The `minSdkVersion` is set to `14` so pre-`13`-checks are no longer relevant.
> Remove no longer relevant Android API version checks.

- .travis.yml
- gradle-mvn-push.gradle
The `apklib` format is an old format (used 5+ years ago?) that predates the `aar` format. It was community driven and used with the Maven tooling. It's not supported by Gradle or Android Studio and I highly doubt that anyone is still using it. This PR removes the related sections from the Gradle scripts.
https://stackoverflow.com/questions/22657466/android-dependencies-apklib-vs-aar-files
> Remove apklib publishing

- library/src/main/java/com/google/maps/android/clustering/algo/NonHierarchicalViewBasedAlgorithm.java
Fix displaying markers on both sides of the International Date Line in `NonHierarchicalViewBasedAlgorithm`.
> Handle wrapping around international date line

- demo/src/main/java/com/google/maps/android/utils/demo/BaseDemoActivity.java
- demo/src/main/java/com/google/maps/android/utils/demo/BigClusteringDemoActivity.java
- demo/src/main/java/com/google/maps/android/utils/demo/ClusteringDemoActivity.java
- demo/src/main/java/com/google/maps/android/utils/demo/CustomMarkerClusteringDemoActivity.java
- demo/src/main/java/com/google/maps/android/utils/demo/DistanceDemoActivity.java
- demo/src/main/java/com/google/maps/android/utils/demo/GeoJsonDemoActivity.java
- demo/src/main/java/com/google/maps/android/utils/demo/HeatmapsDemoActivity.java
- demo/src/main/java/com/google/maps/android/utils/demo/HeatmapsPlacesDemoActivity.java
- demo/src/main/java/com/google/maps/android/utils/demo/IconGeneratorDemoActivity.java
- demo/src/main/java/com/google/maps/android/utils/demo/KmlDemoActivity.java
- demo/src/main/java/com/google/maps/android/utils/demo/PolyDecodeDemoActivity.java
- demo/src/main/java/com/google/maps/android/utils/demo/PolySimplifyDemoActivity.java
- demo/src/main/java/com/google/maps/android/utils/demo/TileProviderAndProjectionDemo.java
- demo/src/main/java/com/google/maps/android/utils/demo/VisibleClusteringDemoActivity.java
Only move the camera to the starting location when not restoring
> Differentiate between initial start and configuration change restore

- library/src/main/java/com/google/maps/android/ui/BubbleDrawable.java
- library/src/main/java/com/google/maps/android/ui/IconGenerator.java
As discussed in https://github.com/googlemaps/android-maps-utils/issues/532#issuecomment-548398116, it seems the deprecated `Drawable getDrawable (int id)` implementation isn't properly handling drawable resource scaling in all cases,
This PR replaces the deprecated `Drawable getDrawable (int id)` with `ContextCompat.getDrawable()` to hopefully fix the intermittent `Resources$NotFoundException` crashes during clustering setup.
> Fix #532 - Use ContextCompat to load drawable resources for scaling

- .travis.yml
- library/build.gradle
- library/src/androidTest/java/com/google/maps/android/data/geojson/GeoJsonPointStyleTest.java
Currently, Travis CI simply builds the library but does not run any of the unit tests. This is because the unit tests are instrumented, and therefore require a running emulator or device to execute. And getting emulators to run on Travis is hard (see https://github.com/googlemaps/android-maps-utils/issues/371).
After a lot of testing, in this PR I've managed to get the magical Travis incantations for running emulators to work. 
We still have one unit test  (`GeoJsonPointStyleTest.testIcon()`) failing on Travis (but not locally) - see **TODO** section below for our options.
I've tested emulators for a number of API Levels (15-19, and 21-29).
Several emulators (15, 16, 19, 29) are broken on Travis - they refuse to start or hang during startup.
Emulators 17, 18, and 21-28 start up correctly …
> Fix #371 - Run emulator-based unit tests on Travis

- .travis.yml
Let's see if API 26 is any better. I used API 26 for a lot of testing of Travis on a separate branch and didn't see any failures then :crossed_fingers:.
> Fix #575 - Use API 26 emulator instead of API 28

- library/src/main/java/com/google/maps/android/data/geojson/GeoJsonParser.java
As a user of the android-maps-utils lib I want to use the geoJson parser standalone to be able of parsing any kind of valid geoJson data with the lib.
> Made GeoJsonParser with parseGeometry public to use parser standalone

- library/src/androidTest/java/com/google/maps/android/data/kml/KmlParserTest.java
- library/src/androidTest/res/raw/amu_empty_hotspot.kml
- library/src/main/java/com/google/maps/android/data/kml/KmlStyleParser.java
This prevents a crash due to NPE when parsing `<hotSpot />` within KML styles.  Test file snippet and new unit test are included.
> Fix #530 - Check for empty KML Style <hotspot> element before parsing

- library/src/androidTest/java/com/google/maps/android/data/kml/KmlStyleTest.java
- library/src/main/java/com/google/maps/android/data/kml/KmlStyle.java
This PR avoids exceptions when parsing KML files that include leading or trailing spaces in colors, like `<color>ff0098e6 </color>`, by trimming leading and trailing whitespace prior to parsing the color. This applies to colors for markers, polylines, and polygons. Unit tests are included.
It turns out KML colors with leading whitespace were already tolerated in the library, but was treated as a special case and assumed that the leading whitespace was actually intended to be a `0`. This behavior in the library was apparently due to previous behavior of Google Map's KML export feature. From `KmlStyle.convertColor()`:
~~~
// Maps exports KML colors with a leading 0 as a space.
if (newColor.substring(0, 1).equals(" ")) {
newColor = "0" + newColor.substring(1, newColor.length());
}
~~~
I've …
> Fix #427 - Trim leading/trailing whitespace in KML colors

- library/src/main/java/com/google/maps/android/clustering/algo/PreCachingAlgorithmDecorator.java
- library/src/main/java/com/google/maps/android/clustering/view/DefaultClusterRenderer.java
Reuse threads from pool instead of creating new thread for every task
> Use thread pools

- library/src/main/java/com/google/maps/android/clustering/algo/NonHierarchicalDistanceBasedAlgorithm.java
Allow overriding getClusteringItems() in NonHierarchicalDistanceBasedAlgorithm subclass outside package.
Fixes https://github.com/googlemaps/android-maps-utils/issues/577
> Make QuadItem protected

- library/src/main/java/com/google/maps/android/clustering/ClusterManager.java
- library/src/main/java/com/google/maps/android/clustering/view/DefaultClusterRenderer.java
Use MarkerCache for two-way lookup between Markers and Clusters, same as used for ClusterItem marker cache. MarkerCache encapsulates the logic for managing two HashMaps independently.
Other changes just resolve lint warnings.
> Use MarkerCache for cluster markers

- demo/src/main/java/com/google/maps/android/utils/demo/MultiLayerDemoActivity.java
This is a small improvement to the `MultiLayerDemoActivity` - it demonstrates setting up a click listener on a collection, which is necessary for receiving click events for your own features when using multiple layers. This process should be documented, so I'm including this in the demo app too.
@arriolac Suggestions for conventional commit type? `feat:` seems like too much, but I'm not sure the rest of the types fit.
> docs: Add click listener to marker collection in multi-layer demo

- demo/src/main/java/com/google/maps/android/utils/demo/KmlDemoActivity.java
Move `KmlLayer` construction to `AsyncTask` `doInBackground()`. Parsing large KML files can be long-running.
> docs(KMLDemoActivity): Demo construct KmlLayer in background

- library/src/main/java/com/google/maps/android/clustering/algo/NonHierarchicalDistanceBasedAlgorithm.java
- library/src/main/java/com/google/maps/android/quadtree/PointQuadTree.java
- library/src/test/java/com/google/maps/android/clustering/QuadItemTest.java
A clustering performance improvement was made in https://github.com/googlemaps/android-maps-utils/pull/368 by switching from using an ArrayList to a HashSet. 
However, ArrayLists maintain insertion order of the elements when iterating over them later, while HashSets do not. Because the cluster has the center of the first element, that center will change if the iteration order of the elements change, which results in clusters changing position when updating an item model and reclustering.
This changes to using a LinkedHashSet, which should give the same constant time performance benefits as the Set for add/remove over the List, but still maintains insertion order.
A unit test for insertion order is also added.
Fixes #615
Refs: 615
> fix(cluster): Maintain insertion order in clusters

- .travis.yml
- build.gradle
- library/build.gradle
Enabling [CodeCov](https://codecov.io) on Travis so that code coverage reports can be generated and evaluated on a per-PR basis.
> build(CodeCov): Enable CodeCov.

- library/src/main/java/com/google/maps/android/clustering/ClusterManager.java
- library/src/main/java/com/google/maps/android/clustering/algo/Algorithm.java
- library/src/main/java/com/google/maps/android/clustering/algo/GridBasedAlgorithm.java
- library/src/main/java/com/google/maps/android/clustering/algo/NonHierarchicalDistanceBasedAlgorithm.java
- library/src/main/java/com/google/maps/android/clustering/algo/PreCachingAlgorithmDecorator.java
- library/src/main/java/com/google/maps/android/clustering/algo/ScreenBasedAlgorithmAdapter.java
- library/src/main/java/com/google/maps/android/clustering/view/DefaultClusterRenderer.java
- library/src/test/java/com/google/maps/android/clustering/QuadItemTest.java
As discussed in https://github.com/googlemaps/android-maps-utils/issues/90, when an item instance is removed, updated, and re-added the `ClusterManager`, the updated item state wouldn't be reflected on the map.
The reason for this is that `DefaultClusterRenderer.CreateMarkerTask.perform()` was using a marker from its own `mMarkerCache` associated with that item to display that item on the map (even if `ClusterManager.clearItems()` was previously called). This resulted in the updated item contents not being reflected on the map, because the cached marker was not updated.
This PR does the following:
* Add new protected methods in `DefaultClusterRenderer` - `onClusterItemUpdated()` and `onClusterUpdated()` - which are called when an existing cached marker is found for an item/cluster when …
> feat(cluster): Support updating existing items

- library/src/main/java/com/google/maps/android/clustering/view/DefaultClusterRenderer.java
As discussed in https://github.com/googlemaps/android-maps-utils/issues/630, refactor the default cluster item rendering implementation from a private method into the protected method `onBeforeClusterItemRendered()`. This allows apps that extend `DefaultClusterRenderer` to easily override the default behavior.
I also made the following style changes to the rendering code to make it easier to read (but doesn't change function):
* Change format of `!(item.getTitle() == null)` to `item.getTitle() != null`.
* Re-order 2nd and 3rd clause of IF to make it clearer that the marker title is set to the snippet if the title text isn't available and the snippet is.
Refs: 630
Fixes #630
> refactor(cluster): Default item rendering to onBeforeClusterItemRendered()

- demo/src/main/java/com/google/maps/android/utils/demo/KmlDemoActivity.java
- demo/src/main/java/com/google/maps/android/utils/demo/MultiLayerDemoActivity.java
- library/src/androidTest/java/com/google/maps/android/data/kml/KmlRendererTest.java
- library/src/main/java/com/google/maps/android/data/Renderer.java
- library/src/main/java/com/google/maps/android/data/kml/KmlLayer.java
- library/src/main/java/com/google/maps/android/data/kml/KmlRenderer.java
- library/src/test/java/com/google/maps/android/data/kml/KmlRendererTest.java
Updating `KmlLayer`, `KmlRenderer`, and `Renderer`, to accept a `Context` instead of a `FragmentActivity`. The former signature and solution presents a couple of issues mentioned in #629.
This change does break configuration change handling for caching images in a way that
retaining state across these changes is now handled by the caller (i.e. by passing in
an `ImagesCache` instance via `KmlLayer` constructor).
Fixes #629 🦕
> fix(KmlLayer): Update constructor to take in a Context instead

- android-maps-utils-ktx/src/main/java/com/google/maps/ktx/LatLng.kt
- android-maps-utils-ktx/src/main/java/com/google/maps/ktx/Polygon.kt
- android-maps-utils-ktx/src/main/java/com/google/maps/ktx/Polyline.kt
- android-maps-utils-ktx/src/main/java/com/google/maps/ktx/core/PolygonOptions.kt
- android-maps-utils-ktx/src/main/java/com/google/maps/ktx/core/SupportMapFragment.kt
- android-maps-utils-ktx/src/main/java/com/google/maps/ktx/geojson/GeoJson.kt
- android-maps-utils-ktx/src/main/java/com/google/maps/ktx/kml/Kml.kt
- library/src/main/java/com/google/maps/android/data/Layer.java
- library/src/main/java/com/google/maps/android/data/geojson/GeoJsonLineStringStyle.java
- library/src/main/java/com/google/maps/android/data/geojson/GeoJsonPolygonStyle.java
- library/src/main/java/com/google/maps/android/data/kml/KmlLayer.java
Took a pass in the `geojson` and `kml` packages to see what we can make Kotlin friendly. The only method I could find that we can improve is the constructor for `GeoJsonLayer` and `KmlLayer`.
_Before_:
```java
GeoJsonLayer layer = new GeoJsonLayer(map, geoJsonFile, null, polygonManager, null, groundOverlayManager);
```
_After_:
```kotlin
val layer = GeoJsonLayer(
map = map,
geoJsonFile = geoJsonFile,
polygonManager = polygonManager,
groundOverlayManager = groundOverlayManager
)
```
Other changes:
* making all extension functions and properties in the kx library `inline` to avoid overhead of new memory allocations when using the ktx aliases vs. using the method/properties directly
* Added `@ColorInt` annotations in `geojson` classes where I found it to be helpful
* Added `@RawRes` …
> feat(ktx): GeoJson and Kml KTX

- gradle-mvn-push.gradle
A couple of things:
* adds task to generate docs i.e. `./gradlew javadoc`
* uploads `sources.jar` and `javadoc.jar` whenever we publish a new version of the lib
Updating http://googlemaps.github.io/android-maps-utils/javadoc/ is not yet automated. 
Relates to #643
> docs: Add gradle task to generate docs.

- README.md
Adding a link in the description part of the README to point to the KTX library.
> docs: Add link to KTX library

- library/src/main/java/com/google/maps/android/clustering/algo/PreCachingAlgorithmDecorator.java
- library/src/main/java/com/google/maps/android/clustering/view/DefaultClusterRenderer.java
This reverts commit 6619f14c (and I added comments to avoid someone using a thread pool again in the future). 
It seems that when a thread pool is used it allows a thread to try and `unlock()` a lock that it did not `lock()`, which [`ReentrantLock`](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/locks/ReentrantLock.html#unlock()) does not allow - "If the current thread is not the holder of this lock then IllegalMonitorStateException is thrown."
I can't reproduce #660 myself, but based on the description and stack trace in #660 it makes sense that this change could cause this issue in certain multi-threaded states.
It would be good to get a release out in the near term with this fix to see if it does indeed resolve the issue.
Fixes #660
> fix: Revert "Use thread pools (#601)"

- gradle-mvn-push.gradle
Reverts part of https://github.com/googlemaps/android-maps-utils/commit/7bbc3c7f9fb91e65264f6968f67dda17e78abc82.
Hopefully fixes #668 (?)
Also, going forward we should probably bump the demo app dependency immediately after publishing the library release artifact to potentially catch issues like this.
> fix: Fix including sources in release

- README.md
Now that we are uploading the `*-javadoc.jar` file, docs are automatically viewable at javadoc.io.
> docs: Update link to Javadoc

- library/src/main/java/com/google/maps/android/clustering/view/DefaultClusterRenderer.java
Attempt to fix NPE in onClusterItemUpdated by swapping the method invocation on the ClusterItem vs. the Marker.
This should work since a null check was performed prior to invoking methods on it.
I couldn't quite repro the crash myself (I was modifying `ClusteringDemoActivity` locally to try to repro) though.
@barbeau if you have any ideas how to repro this I'm happy to check that.
Fixes #673
> fix: NPE on onClusterItemUpdated

- build.gradle
Android Studio 3.6.2 is now available:
https://androidstudio.googleblog.com/2020/03/android-studio-362-available.html
> Update Android Gradle plugin to 3.6.2

- demo/src/main/java/com/google/maps/android/utils/demo/CustomMarkerClusteringDemoActivity.java
See https://github.com/googlemaps/android-maps-utils/issues/655#issuecomment-607965763 - we need to update the custom clustering demo for the best practices surrounding marker caching, following the implementation of https://github.com/googlemaps/android-maps-utils/pull/627 in v1.
This means overriding onClusterUpdated() and onClusterItemUpdated() with the same implementations as onBeforeClusterRendered() and onBeforeClusterItemRendered(), respectively.
> docs: Update custom clustering demo for marker caching

- library/src/main/java/com/google/maps/android/clustering/ClusterItem.java
- library/src/main/java/com/google/maps/android/clustering/view/DefaultClusterRenderer.java
- library/src/test/java/com/google/maps/android/clustering/QuadItemTest.java
Adding nullability annotations to `ClusterItem` for better Kotlin-Java interop. Implementing `ClusterItem` will result in:
```kotlin
class MyModel : ClusterItem {
override fun getPosition(): LatLng {
// return here
}
override fun getTitle(): String? {
// return here
}
override fun getSnippet(): String? {
// return here
}
}
```
> feat: Add nullability annotations to ClusterItem

- README.md
Adding migration guide from v0.x to v1.x.
~Currently in draft.~ 
Feel free to comment for any other feature/configuration that you would like to see explained in this migration guide.
Fixes #686. Relates to #685.
> docs: Adding migration guide to README

- README.md
- build.gradle
Making another release as release 1.3.0 had a missing aar. See https://github.com/googlemaps/android-maps-utils/pull/724#issuecomment-631004556
I verified that the publishing workflow works just fine and I'm able to see the two .aar files in the Nexus Repository Manager. Unclear what caused the aar to be missing. To help catch & debug this in the future,I'd like to merge in #723 before this PR so that publishing logs can be accessed
(1.3.0 was released by running `./gradlew publish` locally on my machine). Once this PR is merged, I'll push a tag to kick off the publishing workflow.
> chore: Release 1.3.1.

- README.md
Based on user feedback (https://github.com/googlemaps/android-maps-utils/issues/747), I'd like to call out the manager objects more explicitly in the README for instantiating the cluster, GeoJSON, and KML layers.
> docs: Call out adding manager objects for constructors

- library/src/main/java/com/google/maps/android/clustering/ClusterManager.java
- library/src/main/java/com/google/maps/android/clustering/view/ClusterRenderer.java
- library/src/main/java/com/google/maps/android/clustering/view/DefaultClusterRenderer.java
- library/src/main/java/com/google/maps/android/collections/MarkerManager.java
As mentioned in #750, we currently support clicking on info windows for markers in the library, but not long clicking. This PR implements long clicking as well.
BREAKING CHANGE: Note that this could be considered a breaking change because `ClusterRenderer` is a `public interface` and may be used outside of the library if apps implemented their own renderer. Also, if apps were doing `map.setOnInfoWindowLongClickListener()` on their own this implementation will break that behavior and force them to use the collection info window long click listener, similar to how info window click listeners are currently handled (see the [Migration Guide](https://github.com/googlemaps/android-maps-utils#adding-a-custom-info-window)).
I've tested this in the demo app with:
~~~ …
> feat!: Add support for setOnInfoWindowLongClickListener() for Markers

- library/src/main/java/com/google/maps/android/clustering/view/DefaultClusterRenderer.java
Previously, when `setMinClusterSize(4)` was called, clusters of size 4 would still be rendered as individual markers instead of clusters (only clusters of size 5 or more would be rendered as individual cluster markers).
With this change, now `setMinClusterSize(4)` will result in clusters of size 4 being rendered as clusters instead of individual markers.
Also add more Javadocs.
Fixes #696 🦕
> fix: Respect setMinClusterSize() correctly when clustering

- library/src/main/java/com/google/maps/android/clustering/ClusterManager.java
- library/src/main/java/com/google/maps/android/clustering/algo/PreCachingAlgorithmDecorator.java
- library/src/main/java/com/google/maps/android/clustering/view/DefaultClusterRenderer.java
Lock and unlock a local algorithm reference. Ensure methods operate on the same algorithm reference during lock, operation, and unlock. Ensure algorithm reference is not replaced while in use.
This crash is caused by calling `ClusterManager.setAlgorithm()` immediately after `ClusterManager.cluster()` such that the `mAlgorithm` reference is changed in the middle of the background cluster task. So `mAlgorithm.lock()` and `mAlgorithm.unlock()` are actually referencing first the old and then the new algorithm. The thread that called `setAlgorithm()` is the one that locks the algorithm and the `AsyncTask` background thread is the one that attempts to unlock it, resulting in the crash.
This bug was introduced in https://github.com/googlemaps/android-maps-utils/pull/506 when the algorithm lock …
> fix: algorithm concurrency

- library/src/main/java/com/google/maps/android/SphericalUtil.java
The first step of the path iteration and the initialized value of the 'prev' point are the same, their distance is zero, ie it does not cause an error, but its calculation is unnecessary
> chore: Optimize computeLength() measurement

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
As mentioned in https://github.com/googlemaps/android-maps-utils/issues/794#issuecomment-713009571, to get Android Gradle Plugin 4.x to work we need to depend on a fork of the `jacoco-android` project. 
Here's the issue in the main `jacoco-android` project:
https://github.com/arturdm/jacoco-android-gradle-plugin/pull/75.
If a new release that includes the fix from that PR is released, we can go back to depending on the main project.
An aside - I tested `classpath 'com.android.tools.build:gradle:4.1.0'` as well, but got a different error that I believe is an Android Gradle Plugin issue - I'll open a separate issue to track that (**EDIT** Opened at https://github.com/googlemaps/android-maps-utils/issues/800).
---
Before submitting your PR, there are a few things you can do to make sure it …
> fix: Bump Gradle/plugin to 6.5/4.0.2, replace jacoco dependency

- library/src/main/java/com/google/maps/android/data/geojson/GeoJsonParser.java
In https://github.com/googlemaps/android-maps-utils/pull/492 the static `GeoJsonParser.parseGeometry()` method was made public based on requests from the community to be able to parse basic geometry objects.
However, as https://github.com/googlemaps/android-maps-utils/issues/785 points out this method ignores FeatureCollections and also doesn't handle styles, bounding boxes, and properties.
This patch makes the `GeoJsonParser` contructor and two getter methods (`getFeatures()` and `getBoundingBox()`) public so developers can use the `GeoJsonParser` in the same way that it's used internally within the library (instantiating it) without needing to instantiate a separate `GeoJsonLayer`.
Better Javadocs have also been added to `parseGeometry()` to explain how it can be used.
---
Before …
> feat: Make GeoJsonParser fully public

- .github/workflows/publish.yml
Keys should have a prefix of `SYNCED_`. This is likely why the publishing workflow was resulting in a 401.
Fixes #763 🦕
> fix: Fix incorrectly named secret keys.

- library/src/main/java/com/google/maps/android/data/kml/KmlStyle.java
If the KML contains `<outline>0</outline>` the parser still believes there is a border on each polygon
before the commit:
after the commit:
the KML
Fixes #826
> fix(KmlStyle): Fix parsing outline tag when its declared but value is '0' 

- .github/workflows/release.yml
Using a different sonatype credential for the release workflow.
> chore: Update sonatype credentials.

- .releaserc
The release workflow has been failing but the logs don't say much. Changing the log info to `--info` to get more insight on what's causing the failures. Relates to #858.
> chore: Change release log output to --info.

- .github/workflows/android.yml
- .github/workflows/release.yml
In an attempt to debug issue #858, this change introduces two changes to the way GitHub workflows function in this repo:
* The `android` workflow will now run on all branches
* The `workflow_dispatch` was added so both `android` and `release` can be manually run. See: https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
> chore: Add workflow_dispatch to all workflows.

- .github/workflows/android.yml
Updating `android.yml` workflow to run the `build` task which will also run `check` and `test`. This change is related to debugging #858
> chore: Change android.yml to run ./gradlew build

- demo/src/gms/java/com/google/maps/android/utils/demo/ClusteringViewModelDemoActivity.java
- demo/src/gms/java/com/google/maps/android/utils/demo/VisibleClusteringDemoActivity.java
- demo/src/v3/java/com/google/maps/android/utils/demo/ClusteringViewModelDemoActivity.java
- demo/src/v3/java/com/google/maps/android/utils/demo/VisibleClusteringDemoActivity.java
- library/src/main/java/com/google/maps/android/clustering/algo/NonHierarchicalViewBasedAlgorithm.java
Clarify that width and height should be passed as dp to NonHierarchicalViewBasedAlgorithm
The calculations used to determine the visible bounds rely on the width and height being passed in as dp. The demo of the algorithm uses pixels which results in markers being rendered outside of the visible screen.
---
> docs: Clarify NonHierarchicalViewBasedAlgorithm docs and fix demos

- gradle.properties
This is Option 1 to fix https://github.com/googlemaps/android-maps-utils/issues/800 as mentioned in https://github.com/googlemaps/android-maps-utils/issues/800#issuecomment-732239657.
Option 2 is presented in PR https://github.com/googlemaps/android-maps-utils/pull/894.
@arriolac What are your thoughts on this vs. Option 2?
This is certainly a simpler fix that keeps the old configuration, but the potential downside is reduced performance. I don't know what the real-world impact on this project is.
Only one of these two PRs should be merged.
---
Fixes #800 🦕
> fix: Remove Gradle configureondemand

- library/src/main/java/com/google/maps/android/clustering/algo/StaticCluster.java
Patch for https://github.com/googlemaps/android-maps-utils/issues/917
> perf: Use LinkedHashSet instead of List in StaticCluster

- .releaserc
The previous regex for semantic-release-replace-plugin matched on a string that was not supposed to be affected by the plugin. Specifically, the string "ext.kotlin_version = '1.5.20'" would be replaced by the plugin to "ext.kotlin_version ='2.2.5'" wherein '2.2.5' is the next version of this library. The fix was to add a word boundary (\b) on the regex so that it only matches on the word "version" and not words suffixed with "version".
Fixes #920 🦕
> chore: Add word boundary on 'version' for semantic-release-replace-plugin

- .releaserc
- build.gradle
Summary:
* Bump version to 2.2.5 which is the correct latest release.
* Escaped boundary character in .releaserc to correctly match on the word "version". Semantic release plugin uses Javascript's RegExp object which I tested in the console (see screenshot).
Fixes #924 🦕
> chore: Bump version to 2.2.5 and fix .releaserc.

- .github/workflows/android.yml
- .github/workflows/release.yml
This official action from Gradle validates the checksums of Gradle Wrapper JAR files present in the source tree and fails if unknown Gradle Wrapper JAR files are found.
See https://github.com/gradle/wrapper-validation-action
This PR is a follow up to https://github.com/googlemaps/android-maps-utils/pull/922
---
> ci: Add official Gradle wrapper validation

- lint-checks/build.gradle
- lint-checks/src/test/java/com/googe/maps/android/lint/checks/GoogleMapDetectorTest.kt
This PR replaces dependabot PRs that attempted to bump the lint library dependencies one-at-a-time:
* https://github.com/googlemaps/android-maps-utils/pull/942
* https://github.com/googlemaps/android-maps-utils/pull/941
* https://github.com/googlemaps/android-maps-utils/pull/938
Newer versions of lint dependencies apparently moved a file (and therefore now require an import for `TestFile`) as well as expanded symbol resolution in test file text, and therefore we were getting an error:
```
Couldn't resolve this import [LintError]
import com.google.android.gms.maps.model.Marker;
```
http://googlesamples.github.io/android-custom-lint-rules/api-guide.html (and the result of the failing test) say:
>"If this import is immaterial to the test, either delete it, or mark
this unit test as allowing …
> chore: Bump and update lint checks

- build.gradle
- library/build.gradle
Build currently says:
>WARNING:DSL element 'dexOptions' is obsolete and should be removed.
It will be removed in version 8.0 of the Android Gradle plugin.
Using it has no effect, and the AndroidGradle plugin optimizes dexing automatically.
Additionaly, the "disablePreDex" property hasn't been used since we've switched to GitHub Actions. The link in the comments to the Android Tools site is also deprecated, so this practice no longer seems to be recommended.
---
> chore: Remove unused dex config

- library-v3/build.gradle
- library/src/main/java/com/google/maps/android/collections/MapObjectManager.java
> fix: MapObjectManager.Collection object order

- demo/build.gradle
Closes  https://github.com/googlemaps/android-maps-utils/issues/973
@arriolac This avoids #973 when running lint on the demo app which should allow the semantic release to pass. It bumps to an alpha version of appcompat to avoid an apparent compatibility issue with AGP7 and the latest stable release for appcompat (v1.3.1), but given that the demo app is using the dependency (and not the library) it shouldn't affect library stability.
---
Fixes #973 🦕
> fix: Bump appcompat to avoid "OnClickXmlDetector called context.getMainProject()" lint error

- .github/workflows/android.yml
Closes https://github.com/googlemaps/android-maps-utils/issues/986.
I've also confirmed that I can reproduce https://github.com/googlemaps/android-maps-utils/issues/973 locally on my machine with the same Gradle command when I revert appcompat back to 1.3.1, so CI should now catch issues like https://github.com/googlemaps/android-maps-utils/issues/973 before release.
---
Fixes https://github.com/googlemaps/android-maps-utils/issues/986 🦕
> ci: Run lint on all CI builds

- library/src/main/java/com/google/maps/android/clustering/view/ClusterRenderer.java
- library/src/main/java/com/google/maps/android/clustering/view/DefaultClusterRenderer.java
My implementation of my feature request - [issue#1097](https://github.com/googlemaps/android-maps-utils/issues/1097)
Closes #1097
> feat: Allow changes to animation duration for marker splitting/merging effects

- .github/workflows/release.yml
Release action [failing](https://github.com/googlemaps/android-maps-utils/actions/runs/3876666515/jobs/6610774150)
cycjimmy/semantic-release-action@v2 runs on Node 12 and v3 runs on Node 16. GitHub has been [warning](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) that it would update actions to run on Node 16.
> chore: update release action dependency for running on Node 16

- library/src/main/java/com/google/maps/android/clustering/view/ClusterRenderer.java
- library/src/main/java/com/google/maps/android/clustering/view/DefaultClusterRenderer.java
The following PRs exposes the method getColor() in the ClusterRenderer. Thus, developers can override this method and provide their own color schema for clusters.
---
Fixes #1121
> feat: exposing getColor function in the ClusterRenderer

- demo/src/main/java/com/google/maps/android/utils/demo/model/MyItem.java
- demo/src/main/java/com/google/maps/android/utils/demo/model/Person.java
- library/src/main/java/com/google/maps/android/clustering/ClusterItem.java
- library/src/main/java/com/google/maps/android/clustering/view/DefaultClusterRenderer.java
- library/src/test/java/com/google/maps/android/clustering/QuadItemTest.java
The following Pull Request adds support to set the z-index order of Markers within a Cluster.
---
Fixes #703
> feat: added z-index to cluster markers

- demo/build.gradle
This fixes #1167. To be clear, I don't think this is a great fix. But I'm not familiar enough with the project to understand why the setup docs reference this `devsite` branch for pulling examples rather than either embedding it directly in the docs or using another method for dynamically updating things. So I've just elected to uprev the hardcoded value here.
The `devsite` branch does not currently build for many other reasons, and so:
1. I didn't try to make this branch build, nor run the tests.
2. I didn't try to manually search for other places in the docs or `devsite` branch which are out of date.
> docs: Uprev recommended android-maps-utils lib version

- library/src/main/java/com/google/maps/android/data/kml/KmlRenderer.java
Pass the correct set of ground overlays from a nested container to properly add to the map.
Fixes #740 🦕
> fix: Add container ground overlays in KML/KMZ

- .github/workflows/release.yml
This PR updates the Java version in the Release Workflow to 17.
> chore: updated Java from default to 17

- .github/workflows/docs.yml
- build.gradle
- library/build.gradle
This PR fixes the doc generation, broken since 3.4.0.
JavaDoc does not like Kotlin, so we are updating it to a more modern documentation framework, Dokka. We are adding also a new flow to upload the documentation to the GitHub pages.
---
Fixes #1248 🦕
> fix: added dokka and fix doc generation

- demo/build.gradle
- demo/src/main/AndroidManifest.xml
- demo/src/main/java/com/google/maps/android/utils/demo/CustomAdvancedMarkerClusteringDemoActivity.java
- demo/src/main/java/com/google/maps/android/utils/demo/MainActivity.java
- demo/src/main/res/layout/map.xml
- library/build.gradle
- library/src/main/java/com/google/maps/android/clustering/view/DefaultAdvancedMarkersClusterRenderer.java
- library/src/main/java/com/google/maps/android/collections/MarkerManager.java
This PR updates our play-services-maps dependency to 18.2.0, introduces support for Advanced Markers and adds a sample.
---
Fixes #1242 🦕
> feat: added support for Advanced Markers

- README.md
Minimum API level should have been raised to 21 with the release of v3.5.0 (raised Maps SDK dependency from v17 to v18).
Requirement for loading Maps SDK dependency separately is gone now with v3.7.0.
> docs: update prerequisites and install instructions

- README.md
- library/src/main/java/com/google/maps/android/StreetViewUtil.kt
Added street view source parameter to `fetchStreetViewData`
Fixes #1260  🦕
> feat: add street view source parameter

- library/src/main/java/com/google/maps/android/data/Style.java
- library/src/main/java/com/google/maps/android/data/kml/KmlStyleParser.java
- library/src/test/java/com/google/maps/android/data/kml/KmlParserTest.java
- library/src/test/resources/amu_empty_hotspot.kml
Fixes #1172
The library currently never parses `<hotSpot>` element in KML, because they are always empty tags. A valid `<hotSpot>` element should be empty, with the necessary attributes like the following:
```xml
<hotSpot x="0.5" y="0.5" xunits="fraction" yunits="fraction"/>
```
I also adjusted the test for parsing `<hotSpot>` to be a valid KML file (none of `x`, `y`, `xunits`, or `yunits` are valid attributes for `<Style>`), and with a valid and invalid `<hotSpot`> in the case of an invalid `<hotSpot>` the default anchor should be used.
Finally, I also added some warnings to clarify that the library only supports `xunits` and `yunits` that have the value `"fraction"`. I would recommend that this clarification is made in the [KML support table in the official developer …
> fix: Correctly parse `<hotSpot>` elements

- library/src/main/java/com/google/maps/android/clustering/algo/GridBasedAlgorithm.java
- library/src/main/java/com/google/maps/android/clustering/algo/NonHierarchicalViewBasedAlgorithm.java
- library/src/main/java/com/google/maps/android/clustering/algo/ScreenBasedAlgorithm.java
The following PR improves documentation for the algorithms used in Clustering.
---
Fixes #1288 🦕
> fix: updated docs for Clustering algorithms

- .github/workflows/docs.yml
This PR will set the PRs coming from the docs.yml workflow as automatically approved for merge, so we don't need to release them manually with each release.
> chore: using auto-merge label

- .github/workflows/docs.yml
The following PR installs [addlicense](https://github.com/google/addlicense/), and runs it before the documentation is generated. At the moment, the header-check step is [failing](https://github.com/googlemaps/android-maps-utils/pull/1414) since the headers have not been added (and the enforcement level changes based on [the sync file](https://github.com/googleapis/repo-automation-bots/tree/main/packages/sync-repo-settings))
> chore: add license header to docs

- demo/src/main/java/com/google/maps/android/utils/demo/ClusteringDiffDemoActivity.java
> chore: Cleaned up cluster diff demo

- .releaserc
This PR fixes a configuration line on the .releaserc flow to change the version after a release has been done.
> fix: changed release config

- build-logic/convention/src/main/kotlin/PublishingConventionPlugin.kt
- build.gradle.kts
The following PR fixes the publish command.
We had before this code in the main build gradle file, which was not being read on the Convention Plugin, which works on a different scope:
```kotlin
artifactId = if (project.name == "library") {
"android-maps-utils"
} else {
null
}
```
One could say: how do we do it on the android-maps-utils? We name the modules as they should be named.
This should fix the generation of the artifact to have the proper artifactId. Checked locally with `./gradlew clean publishToMavenLocal   `
```xml
<?xml version="1.0" encoding="UTF-8"?>
<metadata>
<groupId>com.google.maps.android</groupId>
<artifactId>android-maps-utils</artifactId>
<versioning>
<latest>3.10.0</latest>
<release>3.10.0</release>
<versions>
<version>3.10.0</version>
</versions> …
```
> chore: fix publish command

- library/src/main/java/com/google/maps/android/clustering/view/ClusterRendererMultipleItems.java
This PR introduces a function to set the animation interpolator for the cluster. The current interpolator is lifted out of the Marker animation, since arguably we will have a single animation for the entire cluster. 
This change only applies to the `ClusterRendererMultipleItems` cluster, to gather some feedback before promoting it to the Abstract Cluster (which will introduce a breaking change)
> feat: setting animation on Cluster

- library/src/main/java/com/google/maps/android/clustering/view/ClusterRendererMultipleItems.java
This PR fixes an issue that triggered a ConcurrentModificationException when accessing a list in the new `ClusterRendererMultipleItems`.
Fixes #1483  🦕
> fix: fix for ConcurrentModificationException

- .github/workflows/lint-report.yml
The following PR removes a couple of lines that will prevent lint from running when a branch has been merged into main (which we don't need, since we can't post the results and this must be done via a Pull Request).
> chore: not run lint on push onto main

- gradle/libs.versions.toml
- library/build.gradle.kts
- library/src/main/java/com/google/maps/android/ui/AnimationUtil.java
- library/src/test/java/com/google/maps/android/AnimationUtilTest.kt
The following PR introduces a new method, to modify the duration of the animation in the `AnimationUtil`. In order to keep the API backwards compatible and avoid a breaking change, the previous method is preserved.
Fixes #1504
> feat: added parameter to modify duration to AnimationUtil

- demo/src/main/AndroidManifest.xml
- demo/src/main/java/com/google/maps/android/utils/demo/ClusterAlgorithmsDemoActivity.kt
- demo/src/main/java/com/google/maps/android/utils/demo/MainActivity.java
- demo/src/main/res/layout/activity_cluster_algorithms_demo.xml
- demo/src/main/res/values/arrays.xml
We’ve added a couple of new clustering algorithms this year. Each one has some documentation explaining how it works, but nothing beats a good ol’ sample to show them in action.
New class in Kotlin.
https://github.com/user-attachments/assets/191ed35f-e428-4775-b9ea-d6d6ae7f2af5
> docs: adding sample with Clustering Algorithms

- .github/header-checker-lint.yml
This PR removes the HTML extension from the header-check.
> build: removed HTML extension from header check

- build-logic/convention/src/main/kotlin/PublishingConventionPlugin.kt
This PR modifies the Maven plugin configuration to set it as android-maps-utils, allowing us to publish on Maven Central under this category.
> chore: update Maven configuration

- demo/build.gradle.kts
- gradle/libs.versions.toml
This PR moves the minimum SDK version to the version catalog.
> chore: small tweak to put the minimum SDK into the version catalog
