googlemaps/android-maps-utils

README.md
_config.yml
index.markdown

redcarpet -> kramdown
pygments -> rougue
fixing markdown bugs that broke rendering
R: @domesticmouse

Prepare for incoming gh-pages deprecations

---

_config.yml

Moving to rouge syntax highlighter

---

library/build.gradle

PTAL @jfschmakeit @domesticmouse

Added sourceJar task to library

---

README.md
demo/src/com/google/maps/android/utils/demo/KmlDemoActivity.java

Mostly cleaned up the README:
- Give a better overview by listing the features
- Point developers at the detailed docs on devsite

Misc cleanup

---

library/src/com/google/maps/android/kml/KmlRenderer.java

Dunno why it was an activity...

KML renderer is not an activity

---

demo/src/com/google/maps/android/utils/demo/CustomMarkerClusteringDemoActivity.java

The code in comments may help people easy implement clusters zoom in.
So, please, check is it ok for you team or not?

Zoom in the cluster

---

library/src/com/google/maps/android/clustering/view/DefaultClusterRenderer.java

Please consider merging this as it will make `DefaultClusterRenderer` more flexibel.

Made minimum cluster size configurable

---

demo/build.gradle
library/build.gradle
library/src/com/google/maps/android/kml/KmlFeatureParser.java
library/src/com/google/maps/android/kml/KmlRenderer.java

This adds support for the `drawOrder` element in KML which was originally omitted. 
@samthor PTAL

Kml draw order

---

CONTRIBUTORS.md

Based on the following past contributions:
* https://github.com/googlemaps/android-maps-utils/commit/d7244938e7c7dc31dd398a042ab5d44acd3217e3
* https://github.com/googlemaps/android-maps-utils/commit/807f515f535a4cea06ed8b4299548ed74350a126
* https://github.com/googlemaps/android-maps-utils/commit/919cd2b6cc7c7e27fbabe0e8d7280dbd806058a1

Add self to contributors list

---

demo/AndroidManifest.xml

[Get API Key | Google Maps Android API | Google Developers](https://developers.google.com/maps/documentation/android-api/signup#add_the_api_key_to_your_application)

Updated API key name to match documentation 

---

library/src/com/google/maps/android/clustering/view/DefaultClusterRenderer.java

There was a bug where if a cluster already has a marker on the map when
a cluster operation occurs, the cluster would add a new marker without
reusing the existing marker. The new marker would update the mapping to
`mClusterToMarker`, adding a new mapping in `mMarkerToCluster`, while
leaving the old marker mapped in `mMarkerToCluster`. When the old marker
is then removed, it also removes the new marker's mapping in
`mClusterToMarker`.
This results in there no longer existing a mapping for the cluster in
`mClusterToMarker` and `getMarker()` returns null. If
`OnClusterClickListener.onClusterClick()` wants to do something like this:
```
public boolean onClusterClick(Cluster<ClusterItem> cluster) {
Marker marker = mClusterRenderer.getMarker(cluster);
marker.showInfoWindow(); <-- …
```

Reuse cluster markers in DefaultClusterRenderer

---

library/src/com/google/maps/android/clustering/ClusterManager.java

Add documentation for onClusterClick

---

library/src/com/google/maps/android/data/kml/KmlPlacemark.java

Check for method call over mInlineStyle when it is null

KmlPlacemark method call over mInlineStyle when it is null

---

build.gradle
demo/res/layout/places_demo.xml
demo/src/com/google/maps/android/utils/demo/HeatmapsPlacesDemoActivity.java
gradle/wrapper/gradle-wrapper.properties

Previously the search would only be triggered by the action button on the keyboard. This button is needed when the keyboard doesn't have the action button, e.g. on samsung.

Add go button in Heatmaps-Places demo.

---

library/src/com/google/maps/android/clustering/algo/Algorithm.java
library/src/com/google/maps/android/clustering/algo/GridBasedAlgorithm.java
library/src/com/google/maps/android/clustering/algo/NonHierarchicalDistanceBasedAlgorithm.java
library/src/com/google/maps/android/clustering/algo/PreCachingAlgorithmDecorator.java
library/src/com/google/maps/android/clustering/view/DefaultClusterRenderer.java

Added a setter/getter for the max distance between clustered items in the clustering Algorithm interface and implemented in NonHierarchicalDistanceBasedAlgorithm and GridBasedAlgorithm.

Configurable max distance between clustered items

---

library/src/com/google/maps/android/PolyUtil.java

It would be very useful to follow this tip: https://github.com/googlemaps/android-maps-utils/issues/147#issuecomment-71591603

Expose PolyUtil.locationIndexOnEdgeOrPath()

---

library/src/com/google/maps/android/clustering/view/DefaultClusterRenderer.java

see: https://issuetracker.google.com/issues/35827242

Prevent throw "IllegalArgumentException: left == right"

---

demo/build.gradle
library/build.gradle

update maps lib

---

build.gradle
demo/AndroidManifest.xml
demo/build.gradle
demo/src/com/google/maps/android/utils/demo/BaseDemoActivity.java
demo/src/com/google/maps/android/utils/demo/BigClusteringDemoActivity.java
demo/src/com/google/maps/android/utils/demo/ClusteringDemoActivity.java
demo/src/com/google/maps/android/utils/demo/DistanceDemoActivity.java
demo/src/com/google/maps/android/utils/demo/HeatmapsDemoActivity.java
demo/src/com/google/maps/android/utils/demo/KmlDemoActivity.java
demo/src/com/google/maps/android/utils/demo/VisibleClusteringDemoActivity.java
gradle/wrapper/gradle-wrapper.properties
library/build.gradle
library/src/com/google/maps/android/clustering/algo/GridBasedAlgorithm.java
library/src/com/google/maps/android/clustering/algo/PreCachingAlgorithmDecorator.java
library/src/com/google/maps/android/data/Renderer.java
library/src/com/google/maps/android/heatmaps/HeatmapTileProvider.java

1. Fix build errors
2. Upgrade to androidx
3. Fix some warnings

Fix build error, and upgrade dependencies.

---

library/tests/src/com/google/maps/android/PolyUtilTest.java
library/tests/src/com/google/maps/android/clustering/StaticClusterTest.java
library/tests/src/com/google/maps/android/data/FeatureTest.java
library/tests/src/com/google/maps/android/data/geojson/BiMultiMapTest.java
library/tests/src/com/google/maps/android/data/geojson/GeoJsonFeatureTest.java
library/tests/src/com/google/maps/android/data/geojson/GeoJsonLayerTest.java
library/tests/src/com/google/maps/android/data/geojson/GeoJsonPointStyleTest.java
library/tests/src/com/google/maps/android/data/geojson/GeoJsonRendererTest.java
library/tests/src/com/google/maps/android/data/kml/KmlMultiTrackTest.java
library/tests/src/com/google/maps/android/data/kml/KmlParserTest.java
library/tests/src/com/google/maps/android/data/kml/KmlRendererTest.java
library/tests/src/com/google/maps/android/heatmaps/UtilTest.java

Change JUnit assertion calls.

---

library/src/main/java/com/google/maps/android/heatmaps/HeatmapTileProvider.java

Added maxIntensity functionality that is currently present in the V3 Javascript API. 
"The maximum intensity of the heatmap. By default, heatmap colors are dynamically scaled according to the greatest concentration of points at any particular pixel on the map. This property allows you to specify a fixed maximum. Setting the maximum intensity can be helpful when your dataset contains a few outliers with an unusually high intensity."

Expose MaxIntensity functionality to user

---

gradle/wrapper/gradle-wrapper.properties

Quick patch update to that latest version of the Gradle wrapper
https://docs.gradle.org/5.6.3/release-notes.html

Update Gradle wrapper to 5.6.3

---

library/src/androidTest/java/com/google/maps/android/clustering/QuadItemTest.java
library/src/androidTest/java/com/google/maps/android/data/MultiGeometryTest.java
library/src/androidTest/java/com/google/maps/android/data/RendererTest.java
library/src/androidTest/java/com/google/maps/android/data/geojson/GeoJsonLayerTest.java
library/src/androidTest/java/com/google/maps/android/data/geojson/GeoJsonLineStringStyleTest.java
library/src/androidTest/java/com/google/maps/android/data/geojson/GeoJsonLineStringTest.java
library/src/androidTest/java/com/google/maps/android/data/geojson/GeoJsonMultiLineStringTest.java
library/src/androidTest/java/com/google/maps/android/data/geojson/GeoJsonMultiPointTest.java
library/src/androidTest/java/com/google/maps/android/data/geojson/GeoJsonMultiPolygonTest.java
library/src/androidTest/java/com/google/maps/android/data/geojson/GeoJsonParserTest.java
library/src/androidTest/java/com/google/maps/android/data/geojson/GeoJsonPointStyleTest.java
library/src/androidTest/java/com/google/maps/android/data/geojson/GeoJsonPolygonStyleTest.java
library/src/androidTest/java/com/google/maps/android/data/geojson/GeoJsonPolygonTest.java
library/src/androidTest/java/com/google/maps/android/data/geojson/GeoJsonRendererTest.java
library/src/androidTest/java/com/google/maps/android/data/kml/KmlMultiGeometryTest.java

These are the remaining changes from #556 by @ming13 rebased onto the latest `master`.
<sub><sup>Once approved, please use a *normal* GitHub merge (i.e. **NO rebase/squash** merge) to integrate the commit(s) from the PR head branch. The changes are broken up into meaningful, [atomic commits](https://www.freshconsulting.com/atomic-commits/), and my branch should already be up-to-date with the latest base branch. If it isn't, or if you want me to change anything, please let me know, and I will update the branch as soon as possible. Thank you!</sup></sub>

Change test methods visibility

---

library/src/main/java/com/google/maps/android/data/kml/KmlRenderer.java

Add marker icon recursively to point sub-geometries for multi-geometry placemarks.
Fixes https://github.com/googlemaps/android-maps-utils/issues/460

Recurse over multi-geometry placemarks

---

android-maps-utils-ktx/src/main/java/com/google/maps/ktx/LatLng.kt
android-maps-utils-ktx/src/main/java/com/google/maps/ktx/Polygon.kt
android-maps-utils-ktx/src/main/java/com/google/maps/ktx/Polyline.kt
android-maps-utils-ktx/src/test/java/com/google/maps/ktx/LatLngTest.kt
android-maps-utils-ktx/src/test/java/com/google/maps/ktx/PolylineTest.kt

Adding extension functions and properties for SphericalUtil.
Don't merge just yet—I still need to write unit tests

feat(KTX): Create ktx for SphericalUtil

---

README.md

Updating our README to include more info on:
* how devs can include the library
* how devs can contribute and receive support (filing issues, Discord, etc.)
Note that once merged I'll update this line: https://github.com/googlemaps/android-maps-utils/compare/master...chris/update_readme#diff-04c6e90faac2675aa89e2176d2eec7d8R34 on PR #635

docs(README): Update README with more info.

---

README.md

Add a badge to our README that shows we support chat ![Discord](https://img.shields.io/discord/676948200904589322)

docs: Make Discord more visible

---

.github/blunderbuss.yml

Adding a config file for [Blunderbuss bot](https://github.com/googleapis/repo-automation-bots/tree/master/packages/blunderbuss).
Issues and PRs will be automatically and randomly assigned to one of us @barbeau .

feat: Add blunderbuss.yml config

---

library/build.gradle

chore: Support Java 8

---

demo/src/main/java/com/google/maps/android/utils/demo/MultiLayerDemoActivity.java

Refactor the multi-layer demo activity to be easier to read, and add documentation metadata for code snippets to be used in developer docs.

docs: Refactor multilayer demo for docs, add docs metadata

---

library/src/main/java/com/google/maps/android/PolyUtil.java

Exposing this const so that it is accessible by the KTX library.

chore: Expose PolyUtil.DEFAULT_TOLERANCE

---

CHANGELOG.md
gradle-mvn-push.gradle

chore(Release): 1.0.1

---

CHANGELOG.md
README.md
gradle-mvn-push.gradle

chore(Release): 1.0.2

---

demo/build.gradle

Bump demo app to library v1.0.2

chore: Bump demo app to library v1.0.2

---

.github/ISSUE_TEMPLATE/bug_report.md

I've noticed that developers aren't providing some useful information in reports, like whether the issue they've seen occurs on a real device or emulator, and whether it can be reproduced using the demo app. I've updated the issue template to leave clear space for these details, and also removed some text that doesn't seem relevant to AMU.
I've also added clearer headings for expected vs. observed behavior.
@arriolac If any of this doesn't seem appropriate for this project, let me know and I can remove it.

docs: Update issue template

---

.github/workflows/android.yml
.travis.yml

~~*Please don't merge - work in progress*~~
Simple test with a single build configuration

ci: Add GitHub Actions CI, reduce Travis matrix

---

CHANGELOG.md
README.md
gradle-mvn-push.gradle

chore(Release): 1.1.0

---

library/src/main/java/com/google/maps/android/clustering/ClusterManager.java

Adding JavaDoc for onClusterItemClick. What returning true or false in this method does is a bit confusing so thought we'd document.

docs: Adding javadoc for onClusterItemClick

---

README.md

docs: Readme typo

---

demo/build.gradle
library/build.gradle

For build tools, AMU library (for demo app), lifecycle-extensions

chore: Bump dependency versions

---

README.md

docs: Add v1 migration guide for custom clustering

---

build.gradle

fix: Use correct URL for maven artifact URL.

---

README.md
demo/src/main/java/com/google/maps/android/utils/demo/ClusteringDemoActivity.java
demo/src/main/res/layout/custom_info_window.xml

Add missing code to README on how to set a custom InfoWindowAdapter when using clustering.
Also added code in the demo project showing how this can be done.
Resolves #738

chore: Custom InfoWindowAdapter demo and README.

---

README.md

* Call out more explicitly where Google Play Services is required
* Remove minor version from v3 (since we're now on v3.1 beta)
---
Closes #756

docs: Update Maps SDK v3 support in README

---

.github/workflows/publish.yml

To help troubleshoot https://github.com/googlemaps/android-maps-utils/issues/763

chore: Set publish log level to "debug"

---

demo/src/main/java/com/google/maps/android/utils/demo/HeatmapsPlacesDemoActivity.java

As discussed in #770, the Radar Search API was deprecated a while back. As a result the `HeatmapsPlacesDemoActivity` stopped working.
This PR changes the Heatmap Places demo to use the Nearby Search API instead. It also ensures Toasts are called on the main thread in case of any IO or parsing problems so the app doesn't crash.
---
Fixes #770 🦕

docs: Change Heatmap Places demo Radar Search API -> Nearby Search API

---

.github/workflows/android.yml
.github/workflows/release.yml
.releaserc
README.md
RELEASING.md

Building off of `main`. Once merged, I'll switch the default branch to `main` from `master`. More context: https://github.com/github/renaming

chore: Switching to main.

---

build.gradle
demo/build.gradle
library-v3/build.gradle

chore: Replace JCenter with Maven Central

---

build.gradle
demo/build.gradle
library-v3/build.gradle
library/build.gradle

Add Kotlin dependency to modules so that Kotlin can be used in development alongside Java.
---
Fixes #755 🦕

chore: Support Kotlin as a development language.

---

demo/build.gradle
library-v3/build.gradle
library/build.gradle
lint-checks/build.gradle

Remove noise from build

---

.github/workflows/android.yml

Fixes https://github.com/googlemaps/android-maps-utils/issues/944
---

ci: Add "distribution" to GitHub Action config

---

.github/workflows/android.yml
build.gradle
gradle/wrapper/gradle-wrapper.properties

This is the result of running the upgrade assistant in Android Studio Arctic Fox stable release
---

chore: Update to AGP 7

---

lint-checks/src/test/java/com/google/maps/android/lint/checks/GoogleMapDetectorTest.kt

Fixes typo in package name
---

chore: Refactor lint test package

---

README.md

docs: Add V3 Beta deprecation notice.

---

.gitignore
README.md

Update README with correct release notes that describes V3 BETA deprecation and decommissioning plans.
Fixes #988 🦕

docs: Update README with correct release notes link.

---

build.gradle

This PR fixes an issue with the current semantic release step in CI/CD.
It also removes the 'dexOptions' element, which is obsolete and should be removed. The preDex option is not required either.
---

chore: fixed semantic release issue in CI

---

demo/src/main/java/com/google/maps/android/utils/demo/ClusteringDemoActivity.java

Follow up to implementing the feature in https://github.com/googlemaps/android-maps-utils/pull/752.

docs: Add long click listener to cluster demo

---

library/src/main/java/com/google/maps/android/clustering/view/ClusterRenderer.java
library/src/main/java/com/google/maps/android/clustering/view/DefaultClusterRenderer.java
library/src/main/java/com/google/maps/android/ui/IconGenerator.java

The following PR introduces a function to set the text appearance for a cluster.
---
Fixes #1096 🦕

feat: added function to set text appearance for cluster

---

README.md
demo/src/main/AndroidManifest.xml
demo/src/main/java/com/google/maps/android/utils/demo/AnimationUtilDemoActivity.java
demo/src/main/java/com/google/maps/android/utils/demo/MainActivity.java
library/src/main/java/com/google/maps/android/data/Layer.java
library/src/main/java/com/google/maps/android/ui/AnimationUtil.java

This PR adds an animation util that can be applied beyond just the clustering.
https://user-images.githubusercontent.com/903097/216589088-20432484-e656-4355-9267-350d1a4fffa2.mov
---
Fixes #777 🦕

feat: added animation util

---

README.md

Update README with correct build variant

docs: Update README with correct build variant

---

.releaserc
README.md
demo/build.gradle

chore: update release config to update install snippet version number
chore: update and reorganize README
Fixes #1167

chore: fix code snippet for installation

---

CONTRIBUTING.md
README.md

- Provide links to resources for each utility
- Add contributing guide
- Update Support section

chore: update README

---

library/src/main/java/com/google/maps/android/clustering/view/DefaultClusterRenderer.java

fix: null check in onAnimationUpdate

---

README.md
library/src/main/java/com/google/maps/android/StreetViewUtil.kt

This PR adds the value REQUEST_DENIED to our StreetViewUtil, which allows us to handle this error. It happens when the authentication via API Key fails.
---
Fixes #1234 🦕

fix: added value REQUEST_DENIED to StreetViewUtil

---

.github/workflows/docs.yml

The following PR fixes the Dokka path (using the library one instead of the root folder)
---
Fixes #1248  🦕

fix: fixed Dokka path

---

library/build.gradle

The current PR changes the title of dokka from "library" to "android-maps-utils" 
---
Fixes #1254 🦕

doc: fixed dokka title

---

README.md

This PR changes the documentation link to our GitHub page.
---
Fixes #1252  🦕

docs: changed documentation link

---

.gitignore
build.gradle
demo/build.gradle
gradle/wrapper/gradle-wrapper.properties
lint-checks/build.gradle

chore: bump kotlin to 1.9.22, gradle to 8.2

---

build.gradle
demo/build.gradle
gradle/wrapper/gradle-wrapper.properties
library/build.gradle
lint-checks/build.gradle

chore: Updates Gradle to 8.3.2. Min Android SDK version to 21

---

.github/workflows/test.yml
build.gradle

The following PR adds an action to report JaCoCo on each PR.

chore: added JaCoCo report

---

.github/blunderbuss.yml
.github/dependabot.yml
.github/header-checker-lint.yml
.github/stale.yml
demo/src/main/AndroidManifest.xml
demo/src/main/java/com/google/maps/android/utils/demo/StreetViewDemoActivity.kt
demo/src/main/res/layout/street_view_demo.xml
library/src/main/AndroidManifest.xml
library/src/test/java/com/google/maps/android/StreetViewUtilTest.kt
tools/android-wait-for-emulator.sh

This PR adds a new GitHub flow to check whether our files contain a copyright header.
---
Fixes #1284 🦕

chore: added header checker

---

build.gradle
demo/build.gradle
demo/src/main/AndroidManifest.xml
demo/src/main/java/com/google/maps/android/utils/demo/ApiKeyValidator.kt
demo/src/main/java/com/google/maps/android/utils/demo/BaseDemoActivity.java
demo/src/main/java/com/google/maps/android/utils/demo/ClusteringViewModel.java
demo/src/main/java/com/google/maps/android/utils/demo/MainActivity.java
demo/src/main/java/com/google/maps/android/utils/demo/StreetViewDemoActivity.kt
demo/src/main/res/values/strings.xml
demo/src/test/java/com/google/maps/android/utils/demo/AipKeyValidatorTest.kt
demo/src/test/java/com/google/maps/android/utils/demo/ApiKeyValidatorTest.kt
gradle/wrapper/gradle-wrapper.properties
library/build.gradle

feat: Export the demo activities so they can be run directly
chore: Update gradle version, Google maps to 19.0.0

feat: Try to catch invalid map api keys in the demo

---

.github/workflows/release.yml
.github/workflows/test.yml

The following PR changes the secrets name to reflect the new ones on GitHub.

chore: changed secrets name

---

.github/workflows/release.yml

The following PR upgrades the wrapper validation action.

chore: upgrade wrapper validation

---

README.md

Commit 4038b7aaeb4226f355ab514cbabd1cbfa7fa4cf6 moved the `CustomMarkerClusteringDemoActivity.java` file. This PR adjusts sources to changes.
---

docs: update `CustomMarkerClusteringDemoActivity` reference

---

README.md

This PR fixes a link in the README file.

chore: fix README.md link

---

library/src/main/java/com/google/maps/android/clustering/view/ClusterRendererMultipleItems.java

The following PR adds a line to update an individual item when the clustering has been re-triggered.

fix: fixed item updated

---

.releaserc
README.md
build.gradle.kts

This PR increases the verbosity of the `gradlew publish` command, to be able to debug it better.

chore: increased logging

---

library/src/main/java/com/google/maps/android/clustering/view/ClusterRendererMultipleItems.java

Add public modifier to `setAnimationType()` to help callers call this API
Fixes #1473

fix: Add public modifier to setAnimationType()

---

demo/src/main/java/com/google/maps/android/utils/demo/MainActivity.java

This chore PRs removes an unnecessary check on the `MainActivity`, since it is happening already on the `BaseActivity`.

chore: removed unnecessary check

---

build-logic/convention/src/main/kotlin/PublishingConventionPlugin.kt

This PR sets the artifactId via the coordinates in Vanniktech.

chore: added artifactId

---

demo/build.gradle.kts
demo/src/main/AndroidManifest.xml
demo/src/main/java/com/google/maps/android/utils/demo/MainActivity.java
demo/src/main/java/com/google/maps/android/utils/demo/PolySimplifyDemoActivity.java
demo/src/main/java/com/google/maps/android/utils/demo/PolylineProgressDemoActivity.kt
demo/src/main/res/drawable/baseline_airplanemode_active_24.xml
demo/src/main/res/layout/activity_polyline_progress_demo.xml
demo/src/main/res/values/strings.xml
library/src/main/java/com/google/maps/android/SphericalUtil.kt
library/src/test/java/com/google/maps/android/SphericalUtilTest.java

Refactored `PolylineProgressDemoActivity` to improve code quality, add documentation, and align it with `BaseDemoActivity`.

feat(library): Add polyline progress utilities to SphericalUtil
